'use client'
import { useEffect, useRef, useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Plus, Search, X, ArrowLeft, ArrowUpRight, Check, Clock, Users, LayoutGrid, CalendarDays } from 'lucide-react'
import { CRM_STAGES, CrmContact, CrmTask, CrmEvent, CrmProposal, crmToday, taskTiming } from '@/lib/crm'
import { proposalReference } from '@/lib/proposal-reference'
import { saveContact, changeStage, addCrmNote, addCrmTask, completeCrmTask } from '@/app/painel/comercial/actions'
const field = 'mt-1 w-full rounded-xl border border-white/15 bg-[#141b28] px-3 py-2.5 text-sm text-white focus:outline-none focus:ring-2 focus:ring-blue-500'
const button = 'inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold hover:bg-blue-500 disabled:opacity-40'
const money = (n:number) => n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const eventText = (body:string) => body.startsWith('Etapa: ') ? body.replace(/\b(novo|diagnostico|reuniao|proposta|negociacao|ganho|perdido)\b/g, value => CRM_STAGES.find(s=>s.id===value)?.label ?? value) : body
const date = (s:string) => s.slice(0,10).split('-').reverse().join('/')
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}) {
  const ref = useRef<HTMLDialogElement>(null)
  useEffect(()=>{ref.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[])
  return <dialog aria-label={title} ref={ref} onClose={close} onClick={e=>{if(e.target===ref.current)close()}} className="m-auto w-[min(940px,95vw)] max-h-[92svh] overflow-y-auto rounded-3xl border border-white/15 bg-[#0d1320] p-0 text-white shadow-2xl backdrop:bg-black/70"><header className="sticky top-0 z-10 bg-[#0d1320] border-b border-white/10 p-5 flex items-center justify-between gap-4"><h2 className="text-xl font-bold">{title}</h2><button onClick={close} aria-label="Fechar" className="p-2 rounded-full hover:bg-white/10"><X size={20}/></button></header><div className="p-5 md:p-7">{children}</div></dialog>
}
export default function CrmWorkspace({contacts,tasks,events,proposals}:{contacts:CrmContact[];tasks:CrmTask[];events:CrmEvent[];proposals:CrmProposal[]}) {
  const router=useRouter()
  const [tab,setTab]=useState<'funil'|'contatos'|'retornos'>('funil')
  const [search,setSearch]=useState('')
  const [filter,setFilter]=useState('pendentes')
  const [selected,setSelected]=useState<string|null>(null)
  const [editor,setEditor]=useState<CrmContact|'new'|null>(null)
  const [error,setError]=useState('')
  const [notice,setNotice]=useState('')
  const [pending,startTransition]=useTransition()
  const today=crmToday()
  const current=contacts.find(c=>c.id===selected)
  const visible=contacts.filter(c=>[c.restaurant_name,c.contact_name,c.phone,c.city,c.niche,c.source].join(' ').toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')))
  const visibleIds=new Set(visible.map(c=>c.id))
  const pendingTasks=tasks.filter(t=>!t.completed_at)
  const overdue=pendingTasks.filter(t=>taskTiming(t,today)==='overdue')
  const dueToday=pendingTasks.filter(t=>taskTiming(t,today)==='today')
  const open=contacts.filter(c=>!['ganho','perdido'].includes(c.stage))
  function perform(action:()=>Promise<{error?:string;id?:string}>,done?:()=>void) {
    setError('');setNotice('')
    startTransition(async()=>{try {const result=await action();if(result.error)setError(result.error);else {router.refresh();setNotice('Alteração salva.');done?.()}}catch{setError('Não foi possível salvar. Tente novamente.')}})
  }
  function openContact(id:string){setError('');setNotice('');setSelected(id)}
  function taskRow(t:CrmTask, showName=false) {
    const timing=taskTiming(t,today)
    return <div key={t.id} className="flex items-center justify-between gap-4 py-4 border-b border-white/10"><div className="min-w-0">{showName&&<button onClick={()=>openContact(t.contact_id)} className="text-blue-300 text-xs mb-1">{contacts.find(c=>c.id===t.contact_id)?.restaurant_name}</button>}<p className={`text-sm break-words ${t.completed_at?'line-through text-slate-500':'text-white'}`}>{t.title}</p><p className={`text-xs mt-1 ${timing==='overdue'?'text-rose-400':timing==='today'?'text-amber-300':'text-slate-500'}`}>{date(t.due_date)} · {timing==='done'?'Concluído':timing==='overdue'?'Atrasado':timing==='today'?'Hoje':'Agendado'}</p></div><button disabled={pending} onClick={()=>perform(()=>completeCrmTask(t.id,!t.completed_at))} className="shrink-0 border border-white/15 rounded-lg px-3 py-2 text-xs hover:bg-white/10 disabled:opacity-40" aria-label={`${t.completed_at?'Reabrir':'Concluir'}: ${t.title}`}>{t.completed_at?'Reabrir':<span className="flex items-center gap-1"><Check size={14}/>Concluir</span>}</button></div>
  }
  return <main className="min-h-screen bg-[#090c13] text-white">
    <header className="border-b border-white/10 px-5 md:px-10 py-4 flex flex-wrap items-center justify-between gap-4"><Link href="/painel" className="flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16}/>Painel de propostas</Link><span className="text-xs tracking-[.25em] text-blue-300">PINGUIM / COMERCIAL</span><Link href="/painel/nova-proposta" className="text-sm text-slate-300 flex items-center gap-2">Nova proposta<ArrowUpRight size={16}/></Link></header>
    <div className="p-5 md:p-10 max-w-[1800px] mx-auto">
      <div className="flex flex-wrap justify-between gap-5 items-end"><div><p className="text-blue-400 text-xs tracking-widest uppercase mb-3">Relacionamentos que viram negócios</p><h1 className="text-3xl md:text-4xl font-bold">Seu próximo passo comercial.</h1><p className="text-slate-400 mt-3 text-sm">Contatos, negociações e retornos em um só lugar.</p></div><button className={button} onClick={()=>{setEditor('new');setError('')}}><Plus size={17}/>Novo contato</button></div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-8 mb-8">{[
        ['Em negociação',open.length.toString(),'Honorários potenciais: '+money(open.reduce((sum,c)=>sum+Number(c.estimated_value),0))+'/mês'],
        ['Retornos atrasados',String(overdue.length),'Priorize estes contatos'],['Retornos para hoje',String(dueToday.length),'Sua agenda do dia'],['Negócios ganhos',String(contacts.filter(c=>c.stage==='ganho').length),'Contatos na etapa Ganho']
      ].map(([label,value,hint],i)=><div key={label} className="rounded-2xl border border-white/10 bg-gradient-to-br from-white/[.06] to-transparent p-5"><p className="text-xs text-slate-400">{label}</p><p className={`text-3xl font-bold mt-2 ${i===1&&overdue.length?'text-rose-400':i===2?'text-amber-300':i===3?'text-emerald-400':'text-white'}`}>{value}</p><p className="text-[11px] text-slate-500 mt-2">{hint}</p></div>)}</div>
      <div className="flex flex-wrap items-center justify-between gap-4 mb-6"><div className="flex p-1 bg-white/5 rounded-xl gap-1">{([['funil','Funil',LayoutGrid],['contatos','Contatos',Users],['retornos','Retornos',CalendarDays]] as const).map(([id,label,Icon])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)} className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm ${tab===id?'bg-blue-600 text-white':'text-slate-400 hover:text-white'}`}><Icon size={16}/>{label}</button>)}</div><label className="flex items-center gap-2 border border-white/15 bg-white/[.03] rounded-xl px-3 py-2"><Search size={17} className="text-slate-500"/><input aria-label="Buscar contatos" placeholder="Buscar restaurante, contato ou cidade" value={search} onChange={e=>setSearch(e.target.value)} className="bg-transparent text-sm outline-none w-64 max-w-full"/></label></div>
      {!editor&&!current&&error&&<p role="alert" className="text-rose-300 mb-4">{error}</p>}{notice&&!editor&&!current&&<p role="status" className="text-emerald-400 text-xs mb-3">{notice}</p>}
      {tab==='funil'&&<div className="overflow-x-auto pb-5"><div className="grid grid-cols-7 gap-3 min-w-[1600px]">{CRM_STAGES.map(stage=>{const list=visible.filter(c=>c.stage===stage.id);return <section key={stage.id} className="rounded-2xl border border-white/10 bg-white/[.02] p-3 min-h-72"><div className="flex justify-between items-center pb-3 border-b border-white/10"><h2 className="text-sm font-medium flex items-center gap-2"><span className="w-2 h-2 rounded-full" style={{background:stage.color}}/>{stage.label}</h2><span className="text-xs text-slate-500">{list.length}</span></div><div className="space-y-3 mt-3">{list.map(c=>{const next=pendingTasks.find(t=>t.contact_id===c.id);return <article key={c.id} className="rounded-xl p-3 border border-white/10 bg-[#141b28]"><button onClick={()=>openContact(c.id)} className="text-left w-full"><h3 className="text-sm font-semibold break-words">{c.restaurant_name}</h3><p className="text-xs text-slate-400 mt-1">{c.contact_name||'Responsável a informar'}</p><p className="text-xs text-blue-300 mt-3">{money(c.estimated_value)}/mês</p>{next?<p className={`text-xs mt-3 flex items-center gap-1 ${taskTiming(next,today)==='overdue'?'text-rose-400':'text-amber-200'}`}><Clock size={12}/>{date(next.due_date)} · {next.title}</p>:<p className="text-xs text-slate-500 mt-3">Sem próximo retorno</p>}</button><select aria-label={`Etapa de ${c.restaurant_name}`} disabled={pending} value={c.stage} onChange={e=>perform(()=>changeStage(c.id,e.target.value))} className={`${field} !text-xs !py-2 !mt-4`}>{CRM_STAGES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></article>})}{!list.length&&<p className="text-xs text-slate-600 text-center py-12">Nenhum contato nesta etapa</p>}</div></section>})}</div></div>}
      {tab==='contatos'&&<div className="rounded-2xl border border-white/10 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-500 text-xs bg-white/[.03]"><tr>{['Restaurante / responsável','WhatsApp','Cidade / nicho','Origem','Etapa'].map(h=><th key={h} className="px-5 py-4 font-normal">{h}</th>)}</tr></thead><tbody>{visible.map(c=><tr key={c.id} className="border-t border-white/10 hover:bg-white/[.03]"><td className="px-5 py-4"><button onClick={()=>openContact(c.id)} className="text-left"><span className="text-blue-300 font-medium">{c.restaurant_name}</span><span className="block text-xs text-slate-500 mt-1">{c.contact_name||'Não informado'}</span></button></td><td className="px-5 py-4 whitespace-nowrap">{c.phone||'—'}</td><td className="px-5 py-4 text-slate-400">{c.city||'—'}<span className="block text-xs">{c.niche}</span></td><td className="px-5 py-4 text-slate-400">{c.source||'—'}</td><td className="px-5 py-4">{CRM_STAGES.find(s=>s.id===c.stage)?.label}</td></tr>)}</tbody></table>{!visible.length&&<p className="p-12 text-center text-slate-500">Nenhum contato encontrado. Cadastre seu primeiro restaurante.</p>}</div>}
      {tab==='retornos'&&<section className="rounded-2xl border border-white/10 p-5 max-w-4xl"><div className="flex flex-wrap justify-between gap-4 items-center mb-4"><h2 className="font-semibold">Próximas ações</h2><select aria-label="Filtrar retornos" className="bg-[#141b28] border border-white/10 rounded-lg p-2 text-sm" value={filter} onChange={e=>setFilter(e.target.value)}><option value="pendentes">Todos os pendentes</option><option value="overdue">Atrasados</option><option value="today">Hoje</option><option value="future">Futuros</option><option value="done">Concluídos</option></select></div><p className="text-xs text-slate-500">Lembretes exibidos no painel. Datas no horário da Bahia.</p>{(()=>{const list=tasks.filter(t=>visibleIds.has(t.contact_id)&&(filter==='pendentes'?!t.completed_at:taskTiming(t,today)===filter));return list.length?list.map(t=>taskRow(t,true)):<p className="py-12 text-center text-slate-500 text-sm">Nenhum retorno neste filtro.</p>})()}</section>}
    </div>
    {editor&&<Modal title={editor==='new'?'Novo contato':'Editar contato'} close={()=>{if(!pending)setEditor(null)}}><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);perform(()=>saveContact(editor==='new'?null:editor.id,form),()=>setEditor(null))}}><div className="grid sm:grid-cols-2 gap-4">{([
      ['restaurant_name','Restaurante',true,'text'],['contact_name','Responsável',false,'text'],['phone','WhatsApp (com DDD)',false,'tel'],['email','E-mail',false,'email'],['city','Cidade',false,'text'],['niche','Nicho',false,'text'],['source','Origem do contato',false,'text']
    ] as const).map(([key,label,required,type])=><label key={key} className="text-xs text-slate-400">{label}{required?' *':''}<input name={key} type={type} required={required} maxLength={key==='restaurant_name'?160:200} defaultValue={editor==='new'?'':editor[key]} className={field}/></label>)}<label className="text-xs text-slate-400">Honorários potenciais por mês (R$)<input name="estimated_value" type="number" min="0" max="99999999" step="0.01" defaultValue={editor==='new'?0:editor.estimated_value} className={field}/></label><label className="text-xs text-slate-400">Etapa<select name="stage" defaultValue={editor==='new'?'novo':editor.stage} className={field}>{CRM_STAGES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label className="text-xs text-slate-400">Proposta vinculada<select name="proposal_slug" defaultValue={editor==='new'?'':editor.proposal_slug??''} className={field}><option value="">Sem proposta vinculada</option>{proposals.filter(p=>!p.deleted_at).map(p=><option key={p.slug} value={p.slug}>{proposalReference(p)} · {p.restaurant_name}</option>)}</select></label></div><p className="text-xs text-slate-500 mt-4">Vincular uma proposta não altera automaticamente a etapa nem o status dela.</p>{error&&<p role="alert" className="text-rose-300 text-sm mt-4">{error}</p>}<button disabled={pending} className={`${button} mt-6`}>{pending?'Salvando…':'Salvar contato'}</button></form></Modal>}
    {current&&!editor&&<Modal title={current.restaurant_name} close={()=>{if(!pending)setSelected(null)}}><div className="flex flex-wrap justify-between gap-3 items-center"><div><p className="text-sm text-slate-300">{current.contact_name||'Responsável não informado'}</p><p className="text-xs text-slate-500 mt-1">{[current.city,current.niche,current.source].filter(Boolean).join(' · ')||'Complete os dados deste contato.'}</p></div><button className="text-sm text-blue-300 border border-blue-400/20 rounded-xl px-4 py-2" onClick={()=>setEditor(current)}>Editar cadastro</button></div><div className="grid sm:grid-cols-3 gap-4 py-5 border-b border-white/10"><p className="text-sm text-slate-400 break-words">WhatsApp<br/><span className="text-white">{current.phone||'Não informado'}</span></p><p className="text-sm text-slate-400 break-words">E-mail<br/><span className="text-white">{current.email||'Não informado'}</span></p><label className="text-xs text-slate-400">Etapa<select disabled={pending} value={current.stage} onChange={e=>perform(()=>changeStage(current.id,e.target.value))} className={field}>{CRM_STAGES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label></div>
      {current.proposal_slug&&(()=>{const p=proposals.find(p=>p.slug===current.proposal_slug);return p&&!p.deleted_at?<div className="flex flex-wrap gap-4 text-sm text-blue-300 mt-4"><a href={`/proposta/${p.slug}`} target="_blank" rel="noopener noreferrer">Proposta {proposalReference(p)} ↗</a><a href={`/apresentacao/${p.slug}`} target="_blank" rel="noopener noreferrer">Apresentação ↗</a></div>:<p className="text-xs text-slate-500 mt-4">A proposta vinculada está indisponível. Você pode escolher outra em Editar cadastro.</p>})()}
      {error&&<p role="alert" className="text-rose-300 text-sm mt-4">{error}</p>}{notice&&<p role="status" className="text-emerald-400 text-xs mt-4">{notice}</p>}
      <div className="grid md:grid-cols-2 gap-8 mt-7"><section><h3 className="font-semibold mb-3">Próximo contato</h3><form onSubmit={e=>{e.preventDefault();const el=e.currentTarget;const f=new FormData(el);perform(()=>addCrmTask(current.id,String(f.get('title')),String(f.get('due_date'))),()=>el.reset())}}><label className="text-xs text-slate-400">O que fazer?<input name="title" required maxLength={200} placeholder="Ex.: retornar sobre a proposta" className={field}/></label><label className="text-xs text-slate-400 block mt-3">Data do retorno<input name="due_date" required type="date" min="2000-01-01" max="2100-12-31" defaultValue={today} className={field}/></label><button disabled={pending} className={`${button} mt-3 w-full`}>Agendar retorno</button></form><div className="mt-4">{tasks.filter(t=>t.contact_id===current.id).map(t=>taskRow(t))}</div></section><section><h3 className="font-semibold mb-3">Histórico da negociação</h3><form onSubmit={e=>{e.preventDefault();const el=e.currentTarget;const f=new FormData(el);perform(()=>addCrmNote(current.id,String(f.get('kind')),String(f.get('body'))),()=>el.reset())}}><label className="text-xs text-slate-400">Tipo de registro<select name="kind" className={field}><option value="nota">Anotação</option><option value="reuniao">Reunião</option><option value="ligacao">Ligação</option><option value="whatsapp">WhatsApp</option></select></label><label className="text-xs text-slate-400 block mt-3">O que foi conversado?<textarea name="body" required maxLength={4000} rows={3} placeholder="Objeções, combinados e próximos passos…" className={field}/></label><button disabled={pending} className={`${button} mt-3 w-full`}>Registrar atividade</button></form><div className="mt-6 space-y-5">{events.filter(e=>e.contact_id===current.id).map(e=><article key={e.id} className="border-l border-blue-400/30 pl-4"><p className="text-[11px] text-slate-500">{e.kind==='sistema'?'Atualização':e.kind==='nota'?'Anotação':e.kind==='reuniao'?'Reunião':e.kind==='ligacao'?'Ligação':'WhatsApp'} · {new Date(e.created_at).toLocaleString('pt-BR',{timeZone:'America/Bahia',dateStyle:'short',timeStyle:'short'})}</p><p className="text-sm text-slate-300 whitespace-pre-wrap break-words mt-1">{eventText(e.body)}</p></article>)}</div></section></div>
    </Modal>}
  </main>
}
