'use client'
import {useState,useTransition} from 'react'
import {listAuthorizedMetaAccounts,type MetaAccountList} from '@/app/painel/operacional/meta-actions'
export default function MetaAccountDiscovery(){
 const [result,setResult]=useState<MetaAccountList|null>(null)
 const [pending,start]=useTransition()
 function query(more=false){start(async()=>{try{const next=await listAuthorizedMetaAccounts(more?result?.after:undefined);setResult(next.ok&&more?{...next,accounts:[...new Map([...(result?.accounts??[]),...next.accounts].map(a=>[a.id,a])).values()]}:next)}catch{setResult({ok:false,message:'Não foi possível concluir a consulta. Tente novamente.',accounts:[]})}})}
 return <section className="mb-6 rounded-2xl border border-blue-400/25 bg-blue-500/5 p-6"><h2 className="text-xl font-semibold">Contas autorizadas no Meta</h2><p className="mt-2 text-sm text-slate-400">Consulta somente nomes e identificações. Você escolhe depois quais clientes terão dados importados.</p><button disabled={pending} onClick={()=>query()} className="my-4 rounded-xl bg-blue-600 px-5 py-3 disabled:opacity-50">{pending?'Consultando…':'Consultar contas autorizadas'}</button>{result&&<><p role="status" className={result.ok?'text-blue-200':'text-amber-200'}>{result.message}</p><div className="mt-4 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Conta</th><th className="p-3">ID</th><th className="p-3">Moeda</th><th className="p-3">Status da conta</th></tr></thead><tbody>{result.accounts.map(a=><tr key={a.id} className="border-t border-white/10"><td className="p-3">{a.name}</td><td className="p-3">{a.id}</td><td className="p-3">{a.currency}</td><td className="p-3">{a.status===1?'Ativa':a.status===2?'Desativada':`Código ${a.status}`}</td></tr>)}</tbody></table></div>{result.after&&<button disabled={pending} onClick={()=>query(true)} className="mt-4 text-blue-300">Carregar mais contas</button>}</>}</section>
}
