'use client'
import {currentPeriod} from '@/lib/current-period'
import {useState} from 'react'
import Link from 'next/link'
import PortfolioCharts from './PortfolioCharts'
import OperationsWorkspace from './OperationsWorkspace'
import {groups,formatValue,type Pilot} from '@/lib/operations'
export type OperationsClient={id:string;name:string;pilot?:Pilot}
export default function OperationsPortfolio({clients,error}:{clients:OperationsClient[];error?:string}){
 const [clientId,setClientId]=useState(clients.find(c=>c.pilot)?.id??'all')
 const [selectedPeriod,setPeriod]=useState('')
 const monthNow=currentPeriod().key
 const period=selectedPeriod||'2026-08'
 const [channels,setChannels]=useState(groups.map(g=>g.title))
 const [selected,setSelected]=useState(groups.flatMap(g=>g.metrics.map(m=>m.index)))
 const client=clients.find(c=>c.id===clientId)
 const months=[...new Map(clients.flatMap(c=>c.pilot?.months??[]).map(m=>[m.key,m.label])).entries()].sort((a,b)=>b[0].localeCompare(a[0]))
 const metrics=groups.filter(g=>channels.includes(g.title)).flatMap(g=>g.metrics.filter(m=>selected.includes(m.index)).map(m=>({...m,channel:g.title})))
 return <div className="min-h-screen bg-[#090c13] text-white"><div className="border-b border-white/10 px-5 py-4 md:px-10"><div className="mx-auto flex max-w-7xl flex-wrap items-center gap-4"><Link href="/painel" className="text-sm text-blue-300">← Painel</Link><label className="text-sm">Visualizar<select value={clientId} onChange={e=>setClientId(e.target.value)} className="ml-3 rounded-xl border border-white/15 bg-[#101521] p-3"><option value="all">Todos os clientes</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm">Período<select aria-label="Período dos clientes" value={selectedPeriod} onChange={e=>setPeriod(e.target.value)} className="ml-3 rounded-xl border border-white/15 bg-[#101521] p-3"><option value="">Período inicial do cliente</option><option value={monthNow}>Mês atual · {monthNow.split('-').reverse().join('/')}</option>{months.filter(([key])=>key!==monthNow).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div></div>
 {selectedPeriod===monthNow&&<p className="mx-auto max-w-7xl px-5 py-4 text-sm text-blue-200">Mês em andamento. Exibe os dados disponíveis nas fontes; não ativa sincronização automática. Fontes sem dados neste mês aparecem como não informadas.</p>}
 {error&&<p role="alert" className="p-5 text-amber-200">{error}</p>}
 {client?.pilot?<OperationsWorkspace key={client.id} pilot={client.pilot} selectedPeriod={selectedPeriod} onPeriodChange={setPeriod}/>:client?<div className="mx-auto max-w-7xl p-10"><h1 className="text-3xl">{client.name}</h1><p className="mt-5 text-slate-400">Fonte de métricas ainda não conectada para este cliente. Assim que a planilha ou integração for vinculada, o histórico e o relatório poderão ser exibidos aqui.</p><button onClick={()=>setClientId('all')} className="mt-6 text-blue-300">Voltar à visão de todos os clientes</button></div>:<main className="mx-auto max-w-7xl p-5 md:p-10"><p className="text-xs uppercase tracking-widest text-blue-400">Operacional / Visão da carteira</p><h1 className="my-4 text-3xl font-semibold">Todos os clientes, no mesmo painel.</h1><p className="mb-6 text-sm text-slate-400">Clientes aprovados para o operacional, com proposta aprovada ou etapa Ganho no comercial. Apenas fontes conectadas exibem resultados; valores ausentes não representam zero.</p><label className="text-sm">Mês<select value={period} onChange={e=>setPeriod(e.target.value)} className="ml-3 rounded-lg bg-[#101521] p-3"><option value={monthNow}>Mês atual · {monthNow}</option>{period!==monthNow&&!months.some(([key])=>key===period)&&<option value={period}>{period}</option>}{months.filter(([key])=>key!==monthNow).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 <details className="my-6 rounded-2xl border border-white/10 p-5"><summary className="cursor-pointer">Selecionar canais e métricas · {metrics.length} indicadores</summary><div className="mt-5 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{groups.map(g=><fieldset key={g.title}><legend><label className="flex gap-2 font-semibold text-blue-300"><input type="checkbox" checked={channels.includes(g.title)} onChange={()=>setChannels(old=>old.includes(g.title)?old.filter(x=>x!==g.title):[...old,g.title])}/>{g.title}</label></legend>{g.metrics.map(m=><label key={m.index} className="mt-3 flex gap-2 text-sm text-slate-300"><input type="checkbox" disabled={!channels.includes(g.title)} checked={selected.includes(m.index)} onChange={()=>setSelected(old=>old.includes(m.index)?old.filter(x=>x!==m.index):[...old,m.index])}/>{m.label}</label>)}</fieldset>)}</div></details>
 <PortfolioCharts clients={clients} period={period} indices={metrics.map(m=>m.index)}/>
 <h2 className="mb-4 text-xl font-semibold">Tabela completa de clientes e indicadores</h2>
 {!metrics.length?<p className="text-amber-200">Selecione pelo menos uma métrica e seu canal.</p>:<div className="overflow-auto rounded-2xl border border-white/10"><table className="w-full text-left text-sm"><thead><tr><th className="p-4">Cliente / fonte</th>{metrics.map(m=><th key={m.index} className="min-w-36 p-4"><span className="block text-xs font-normal text-blue-300">{m.channel}</span>{m.label}</th>)}</tr></thead><tbody>{clients.map(c=>{const month=c.pilot?.months.find(m=>m.key===period);return <tr key={c.id} className="border-t border-white/10"><th className="min-w-48 p-4"><button onClick={()=>setClientId(c.id)} className="text-left text-blue-200">{c.name} ↗</button><span className="mt-1 block text-xs font-normal text-slate-500">{c.pilot?.error?'Erro ao consultar fonte':month?'Planilha conectada':c.pilot?'Sem dados neste mês':'Fonte não conectada'}</span></th>{metrics.map(m=><td key={m.index} className="whitespace-nowrap p-4">{month?formatValue(month.values[m.index],m.kind):'—'}</td>)}</tr>})}</tbody></table></div>}
 {!clients.length&&<p className="mt-6 text-slate-400">Nenhum cliente ativo disponível. Os ganhos do comercial e propostas aprovadas aparecerão aqui.</p>}
 <p className="mt-5 text-xs text-slate-500">Filtros desta visão ficam nesta sessão e não alteram as consultas individuais do Meta Ads.</p></main>}
 </div>
}
